OPENEUROPA-2178: Media creation entity browser widget.
openeuropa/oe_media pull request #123
Opened 2020-08-19 07:58 UTC by upchuk

2020-09-21 09:56 UTC, nagyad requested changes
Why there is no companion ewcms PR for this?

2020-09-21 09:56 UTC, nagyad commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> + * Entity browser widget linking to the AV Portal service for uploading videos.
This needs to be rephrased.

2020-09-21 09:56 UTC, nagyad commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> +    $bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('media');
We should implement ContainerFactoryPluginInterface, therefor we make use of dependency injection here.

2020-09-21 09:56 UTC, nagyad commented on tests/FunctionalJavascript/MediaCreationFormWidgetTest.php
> +    $this->assertSession()->pageTextContains('Test image');
I would also assert for the presence of the Remove button, since the text can be in the page without having the media referenced.

2020-09-22 06:44 UTC, nagyad commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> +          'Drupal\inline_entity_form\ElementSubmit',
I think we have to put the inline_entity_form module as dependency to this module.

2020-09-22 10:00 UTC, nagyad approved these changes

2020-09-24 07:34 UTC, upchuk reviewed
The new widget should not replace anything from the demo or from the tests. We create a new widget, we need a new test for it.

2020-10-13 10:02 UTC, brummbar requested changes

2020-10-13 10:02 UTC, brummbar commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> +  public function submit(array &$element, array &$form, FormStateInterface $form_state) {
This is the same as the entity form plugin one, let's add a todo (inside the method, so we don't have to repeat the function docblock).

2020-10-13 10:02 UTC, brummbar commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> +      );
I know this is copied from the other, but let's indent properly
```suggestion
      array_walk($entities, function (EntityInterface $entity) {
        $entity->save();
      });
```

2020-10-14 14:10 UTC, brummbar requested changes

2020-10-14 14:10 UTC, brummbar commented on tests/FunctionalJavascript/MediaCreationFormWidgetTest.php
> +  }
I missed this, there's a method `::getOptions()` that already does this.

2020-10-15 07:28 UTC, 22Alexandra commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> +    $bundle = isset($user_input['media_bundle']) ? $user_input['media_bundle'] : NULL;
I'm not sure I got this right.

2020-10-19 16:04 UTC, brummbar approved these changes

2020-10-20 11:05 UTC, sergepavle reviewed
Few comments.

2020-10-20 11:21 UTC, 22Alexandra commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> +    return NestedArray::getValue($form, array_merge([
I'm not sure I understand this comment. There are 2 arguments.

2020-10-20 11:21 UTC, 22Alexandra commented on composer.json
> +        "instaclick/php-webdriver": "^1.4.5",
Done

2020-10-20 11:43 UTC, 22Alexandra commented on src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
> +    return NestedArray::getValue($form, array_merge([
Check with @sergepavle. Fixed.

2020-10-20 11:43 UTC, sergepavle approved these changes

2020-10-21 07:43 UTC, brummbar approved these changes

2020-10-21 07:45 UTC, merged