EWPP-303: Fixing tests related to impact of webtools behavior.
openeuropa/oe_media pull request #130
Opened 2020-10-13 14:15 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-10-20 09:53 UTC, brummbar requested changes
Nice solution you adopted, I like it!

2020-10-20 09:53 UTC, brummbar commented on tests/Behat/WebtoolsContext.php
> +    if ($this->browserSupportsJavaScript()) {
Let's negate this so we can run a simpler assertion (the one at line 113) and return.

2020-10-20 09:53 UTC, brummbar commented on tests/Behat/WebtoolsContext.php
> +          xhr.send(null);
```suggestion
          xhr.send();
```

2020-10-20 09:53 UTC, brummbar commented on tests/Behat/WebtoolsContext.php
> +      $doc->loadHTML($raw_html);
Let's follow what core does in `\Drupal\Component\Utility\Html::load()`:
```suggestion
      $doc = new \DOMDocument();
      @$doc->loadHTML($raw_html);
```

2020-10-20 09:53 UTC, brummbar commented on tests/Behat/WebtoolsContext.php
> +      // Receive unchanged HTML of the current page by ajax.
```suggestion
      // Retrieve the unprocessed page HTML with AJAX.
      // JS-enabled drivers execute scripts that might modify the markup. In order to retrieve the unprocessed
      // HTML, reload the page with AJAX, so all the cookies are passed. Note that this works only for pages loaded
      // with GET.
```

2020-10-20 09:53 UTC, brummbar commented on tests/Behat/WebtoolsContext.php
> +   * Asserts webtools json presence regardless the javascript availability.
Webtools and JSON. Javascript.

2020-10-22 09:37 UTC, brummbar approved these changes

2020-10-27 06:37 UTC, 22Alexandra approved these changes

2020-10-27 08:04 UTC, merged