EWPP-472: Allow remote files in Document media bundle.
openeuropa/oe_media pull request #131
Opened 2020-10-30 07:08 UTC by 22Alexandra

2020-11-06 11:34 UTC, 22Alexandra commented on src/Plugin/Validation/Constraint/DocumentMediaConstraint.php
> +   * Message shown when the remote file is missing.
```suggestion
   * Message shown when the file type is missing.
```

2020-11-06 11:35 UTC, 22Alexandra commented on oe_media.post_update.php
> +  $module_installer->install(['options', 'file_link']);
```suggestion
  \Drupal::service('module_installer')->install(['options', 'file_link']);
```

2020-11-06 11:38 UTC, 22Alexandra commented on tests/Kernel/DocumentMediaTest.php
> +   * Tests that the the correct field keeps the value depending on the type.
```suggestion
   * Tests that the correct field keeps the value depending on the type.
```

2020-11-09 15:05 UTC, imanoleguskiza requested changes

2020-11-09 15:39 UTC, 22Alexandra commented on tests/Functional/DocumentMediaTest.php
> +    $assert_session = $this->assertSession();
The behat scenario. here is not enough? https://github.com/openeuropa/oe_media/pull/131/files#diff-0df9a816419d7a9cceb781c2310ecdc2b6da3352073332a410769098589408d4R58-R71

2020-11-10 07:48 UTC, upchuk commented on tests/Functional/DocumentMediaTest.php
> +    $assert_session = $this->assertSession();
Yes, it's covered in Behat, both for regular and IEF embed no?

2020-11-10 09:32 UTC, imanoleguskiza submitted a review, later dismissed

2020-11-11 09:21 UTC, upchuk approved these changes

2020-11-11 09:21 UTC, hernani approved these changes

2020-11-11 09:21 UTC, merged