EWPP-417: CreateS new Webtools OP Publication List media type.
openeuropa/oe_media pull request #138
Opened 2020-12-03 13:53 UTC by 22Alexandra

2020-12-04 08:23 UTC, georgebaev commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#type'] = 'textfield';
I was able to submit the `1234.56` decimal value in this field. This field should allow integer values only. Could the Number field type at https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21Number.php/class/Number/8.9.x be an option?

2020-12-04 08:27 UTC, georgebaev commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    if (!is_numeric($element['#value'])) {
If we implemented the field as a `number`, then I think this validation could be more appropriate: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21Number.php/function/Number%3A%3AvalidateNumber/8.9.x

2020-12-04 08:33 UTC, georgebaev commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +      $item_values['value'] = '{ "service": "opwidget", "widgetId": "' . $id . '" }';
Could we use https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Serialization%21Json.php/function/Json%3A%3Aencode/8.9.x instead of creating the JSON value manually?

2020-12-04 08:42 UTC, georgebaev commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    return TRUE;
Could we change this functionality to:
```
if (parent::isApplicable($field_definition) &&
    $field_definition->getTargetEntityTypeId() === 'media' &&
    $target_bundle === 'webtools_op_publication_list') {
    return TRUE;
}
return FALSE;
```
My idea is to "insist" on the requirements instead of "filter out" all other requirements. Please ignore this if this is your personal style of coding.

2020-12-04 08:49 UTC, georgebaev commented on modules/oe_media_webtools/tests/src/FunctionalJavascript/OpPublicationListMediaTest.php
> +    $this->assertSession()->pageTextContains('The Webtools OP Publication lists snippet has to contain only digits.');
Can you please test that decimal values are not accepted also?

2020-12-04 08:51 UTC, georgebaev requested changes
Can you please address my comments? Thank you.

2020-12-04 09:36 UTC, 22Alexandra commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#type'] = 'textfield';
OpPublicationListIdWidget::massageFormValues will form a string so we need to keep the element type as "textfield".

2020-12-04 09:50 UTC, 22Alexandra commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +      $item_values['value'] = '{ "service": "opwidget", "widgetId": "' . $id . '" }';
We have a custom constraint for the snippet field would fail when the provided value is not string:
\Drupal\oe_webtools_media\Plugin\Validation\Constraint\WebtoolsMediaConstraintValidator::validate

2020-12-04 10:05 UTC, 22Alexandra commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#type'] = 'textfield';
Updated the validation.

2020-12-04 10:45 UTC, georgebaev approved these changes

2020-12-04 19:37 UTC, drishu requested changes
Just one issue found, all in all nice work.

2020-12-04 19:37 UTC, drishu commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +
<img width="655" alt="Screenshot 2020-12-04 at 21 01 41" src="https://user-images.githubusercontent.com/11507647/101204628-2c76f880-3675-11eb-8e84-e059df3b80f7.png">

```suggestion
    $element['value']['#value'] = $this->transformJsonToId();
```
or something of sorts, we transform the value to json in massageFormValues so we need to transform it back to an id for the edit form.

2020-12-04 19:37 UTC, drishu commented on modules/oe_media_webtools/tests/src/FunctionalJavascript/OpPublicationListMediaTest.php
> +    'oe_media_demo',
we only need `oe_media_demo` the rest can go

2020-12-07 08:16 UTC, 22Alexandra commented on modules/oe_media_webtools/tests/src/FunctionalJavascript/OpPublicationListMediaTest.php
> +    'oe_media_demo',
Indeed

2020-12-07 10:44 UTC, imanoleguskiza requested changes

2020-12-07 10:44 UTC, imanoleguskiza commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +      if (str_contains($items[$delta]->getValue()['value'], '{ "service": "opwidget", "widgetId": "')) {
Instead of relying on string methods, we can just try to json_decode the value. If the return is null, something wen't wrong and we should notify the user. If the return is ok, we can just get the widgetId value directly.

2020-12-07 10:44 UTC, imanoleguskiza commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#type'] = 'textfield';
Lets juts a number element here and remove the custom validation.

2020-12-08 16:27 UTC, imanoleguskiza submitted a review, later dismissed

2020-12-09 13:50 UTC, nagyad requested changes
Please create EPIC-Oplist branch from master and open this PR against that branch. 
Please create a readme for oe_media_webtools module and include what does this module provide, like the widget for example.

2020-12-09 13:50 UTC, nagyad commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    }
```suggestion
    if (!parent::isApplicable($field_definition) ||
      $field_definition->getTargetEntityTypeId() !== 'media' ||
      $field_definition->getTargetBundle() !== 'webtools_op_publication_list'
    ) {
      return FALSE;
    }
```

2020-12-09 13:50 UTC, nagyad commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#description'] = $this->t('Enter the widget id of the snippet generated in <a href="https://op.europa.eu/en/my-widgets" target="_blank">OP Website</a>.');
... generated on the <a...

2020-12-09 15:08 UTC, nagyad approved these changes

2020-12-11 07:19 UTC, upchuk submitted a review, later dismissed

2020-12-11 07:19 UTC, upchuk commented on modules/oe_media_webtools/README.md
> +The module also provides a custom field widget `OP Publication List ID` which converts the given id
Is this readme info relevant? Not like it's a piece of functionality others will use separately..

2020-12-11 07:19 UTC, upchuk commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#description'] = $this->t('Enter the widget id of the snippet generated on the <a href="https://op.europa.eu/en/my-widgets" target="_blank">OP Website</a>.');
We change the description but we should also the label since we are not inputting a `Webtools OP Publication lists snippet` but an ID...

2020-12-11 07:19 UTC, upchuk commented on modules/oe_media_webtools/tests/src/FunctionalJavascript/OpPublicationListMediaTest.php
> +   * Modules to enable.
inheritdoc

2020-12-11 07:19 UTC, upchuk commented on modules/oe_media_webtools/tests/src/Kernel/OpPublicationListIdWidgetTest.php
> +   * Modules to install.
inheritdoc

2020-12-11 07:19 UTC, upchuk commented on modules/oe_media_webtools/tests/src/Kernel/OpPublicationListIdWidgetTest.php
> +    'oe_webtools_media',
protected...

2020-12-11 15:37 UTC, brummbar requested changes

2020-12-11 15:37 UTC, brummbar commented on modules/oe_media_webtools/tests/src/FunctionalJavascript/OpPublicationListMediaTest.php
> +  public function testOpPublicationMedia(): void {
1. Why we are using a javascript test?
2. We are not testing the rendering.

2020-12-14 15:07 UTC, imanoleguskiza approved these changes

2020-12-14 16:36 UTC, brummbar requested changes

2020-12-14 16:36 UTC, brummbar commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#description'] = $this->t('Enter the widget id of the snippet generated on the <a href="@op_widget_url" target="_blank">OP Website</a>.', ['@op_widget_url' => 'https://op.europ
```suggestion
    $element['value']['#description'] = $this->t('Enter the widget id of the snippet generated on the <a href=":op_widget_url" target="_blank">OP Website</a>.', [':op_widget_url' => 'https://op.europa.eu/en/my-widgets']);
```

2020-12-14 16:36 UTC, brummbar commented on modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
> +    $element['value']['#description'] = $this->t('Enter the widget id of the snippet generated on the <a href="@op_widget_url" target="_blank">OP Website</a>.', ['@op_widget_url' => 'https://op.europ
build/core/lib/Drupal/Component/Render/FormattableMarkup.php:32

2020-12-15 08:07 UTC, imanoleguskiza approved these changes

2020-12-15 09:39 UTC, brummbar approved these changes

2020-12-15 14:35 UTC, merged