EWPP-582: Create the Iframe media type.
openeuropa/oe_media pull request #141
Opened 2020-12-04 12:11 UTC by yenyasinn

## EWPP-582

Added new media type "Iframe".

2020-12-04 16:06 UTC, sergepavle approved these changes

2020-12-07 13:40 UTC, 22Alexandra approved these changes

2020-12-09 15:31 UTC, nagyad approved these changes

2020-12-09 15:32 UTC, nagyad requested changes
Let's update the module readme.

2020-12-10 09:34 UTC, nagyad submitted a review, later dismissed

2020-12-15 22:18 UTC, sergepavle commented on README.md
> +* Iframes
Looks like it was missed before also `Video iframe` in lists

2020-12-16 08:27 UTC, yenyasinn commented on README.md
> +* Iframes
@sergepavle, fixed.

2020-12-16 08:47 UTC, sergepavle submitted a review, later dismissed

2020-12-16 12:19 UTC, sergepavle approved these changes

2020-12-16 12:52 UTC, 22Alexandra approved these changes

2020-12-17 16:13 UTC, merged