EWPP-1124: Change filter plugin id to avoid collision with core plugins.
openeuropa/oe_media pull request #164
Opened 2021-05-19 14:27 UTC by imanoleguskiza

## EWPP-1124
### Description

 Change embed_media filter plugin id to avoid collision with the embed_media core plugin.

### Change log

- Added:
- Changed:embed_media media renamed to oe_embed_media
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-05-20 08:24 UTC, sergepavle approved these changes

2021-05-20 12:23 UTC, nagyad requested changes

2021-05-20 12:23 UTC, nagyad commented on modules/oe_media_embed/oe_media_embed.post_update.php
> +      if ($filter['provider'] == 'oe_media_embed' && $filter['id'] === 'media_embed') {
===

2021-05-20 12:31 UTC, nagyad approved these changes

2021-05-20 12:32 UTC, sergepavle submitted a review, later dismissed

2021-06-24 14:17 UTC, nagyad approved these changes

2021-06-24 14:18 UTC, upchuk approved these changes

2021-06-24 14:18 UTC, merged