EWPP-1112: Place Iframe media format after Plain text format.
openeuropa/oe_media pull request #165
Opened 2021-05-20 12:36 UTC by yenyasinn

2021-05-20 14:37 UTC, brummbar requested changes

2021-05-20 15:54 UTC, yenyasinn commented on modules/oe_media_iframe/oe_media_iframe.post_update.php
> +function oe_media_iframe_post_update_00007(): void {
Actually it is true because filter module sets format's weight as it wants so I update oe_media_iframe format based on plain_text format. But it can be moved to ewcms.

2021-05-20 20:39 UTC, brummbar commented on modules/oe_media_iframe/oe_media_iframe.post_update.php
> +function oe_media_iframe_post_update_00007(): void {
Yes let's move it there, we don't know how many custom formats there could be in a website and they might have reordered already accordingly.

2021-05-21 06:58 UTC, brummbar approved these changes

2021-05-21 06:59 UTC, upchuk approved these changes

2021-05-21 06:59 UTC, imanoleguskiza approved these changes

2021-05-21 07:03 UTC, merged