EWPP-845: Create Javascript asset media type and source.
openeuropa/oe_media pull request #167
Opened 2021-06-17 10:47 UTC by nagyad

2021-06-18 11:41 UTC, brummbar requested changes
The ticket didn't say about reading values from enviroment values, but from a settings file. Blocking this until further info is provided or approach is fixed.

2021-06-18 13:37 UTC, brummbar requested changes

2021-06-23 07:17 UTC, brummbar requested changes

2021-06-23 07:17 UTC, brummbar commented on modules/oe_media_js_asset/config/install/media.type.javascript_asset.yml
> +  thumbnails_directory: 'public://media_avportal_thumbnails'
🤔 Did you copy the yml instead of exporting a newly created one?

2021-06-23 07:17 UTC, brummbar commented on modules/oe_media_js_asset/oe_media_js_asset.info.yml
> +    - oe_media_js_asset.settings
We don't need this line to be re-exported with devel.

2021-06-25 06:46 UTC, brummbar requested changes

2021-06-25 06:46 UTC, brummbar commented on modules/oe_media_js_asset/tests/src/Functional/JavaScriptAssetTest.php
> +class JavaScriptAssetTest extends JavaScriptAssetTestBase {
We are just testing the item here, we don't need a full javascript test. This should be kernel.

2021-07-12 13:17 UTC, brummbar requested changes

2021-07-12 13:17 UTC, brummbar commented on modules/oe_media_js_asset/tests/src/Kernel/JavaScriptAssetTest.php
> +  public function testJavaScriptAssetMediaItem() {
Let's add in this method test coverage for the `isEmpty` method.

2021-07-15 11:58 UTC, brummbar approved these changes

2021-07-19 10:42 UTC, sergepavle requested changes

2021-07-19 10:42 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldType/JavaScriptAssetUrlItem.php
> +          'length' => 2028,
Is it safe to use such a length value? In this case, we are assuming that MySQL of component users is >5.0.3

2021-07-19 10:42 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldType/JavaScriptAssetUrlItem.php
> +        ],
Does it make sense here, in this case, to use `NOT NULL  => TRUE,` (as we anyway considering field without environment OR path value as empty)?

2021-07-19 10:42 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldWidget/JavaScriptAssetUrlWidget.php
> +  public function __construct($plugin_id, $plugin_definition, FieldDefinitionInterface $field_definition, array $settings, array $third_party_settings, ConfigFactory $configFactory) {
```suggestion
  public function __construct($plugin_id, $plugin_definition, FieldDefinitionInterface $field_definition, array $settings, array $third_party_settings, ConfigFactoryInterface $configFactory) {
```

2021-07-19 10:42 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldWidget/JavaScriptAssetUrlWidget.php
> +      '#default_value' => !$item->isEmpty() ? $item->environment : '',
```suggestion
      '#default_value' => !$item->isEmpty() ? $item->environment : NULL,
```

2021-07-19 10:42 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldWidget/JavaScriptAssetUrlWidget.php
> +      '#default_value' => !$item->isEmpty() ? $item->path : '',
```suggestion
      '#default_value' => !$item->isEmpty() ? $item->path : NULL,
```

2021-07-19 10:42 UTC, sergepavle commented on modules/oe_media_js_asset/tests/src/Functional/JavaScriptAssetUrlWidgetTest.php
> +    $this->assertSession()->pageTextContains('JavaScript asset First JavaScript asset has been created.');
Can we have also test steps for checking that the media entity is really saved?

2021-07-19 10:42 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldType/JavaScriptAssetUrlItem.php
> +          'length' => 2028,
Did you mean `2048` value?

2021-07-19 10:53 UTC, nagyad commented on modules/oe_media_js_asset/src/Plugin/Field/FieldType/JavaScriptAssetUrlItem.php
> +          'length' => 2028,
Core already uses this in url and link field.

2021-07-19 11:00 UTC, nagyad commented on modules/oe_media_js_asset/src/Plugin/Field/FieldWidget/JavaScriptAssetUrlWidget.php
> +      '#default_value' => !$item->isEmpty() ? $item->environment : '',
Why? In core they use the one I used for string fields on the form.

2021-07-19 11:02 UTC, nagyad commented on modules/oe_media_js_asset/tests/src/Functional/JavaScriptAssetUrlWidgetTest.php
> +    $this->assertSession()->pageTextContains('JavaScript asset First JavaScript asset has been created.');
We could, but in a subsequent tickets we already do that, do we need that here in the widget test?

2021-07-19 12:57 UTC, sergepavle commented on modules/oe_media_js_asset/tests/src/Functional/JavaScriptAssetUrlWidgetTest.php
> +    $this->assertSession()->pageTextContains('JavaScript asset First JavaScript asset has been created.');
It would be nice to have because this feature in fact not related directly to EWPP and any other site owner could use this media type.

2021-07-19 12:58 UTC, sergepavle approved these changes

2021-07-19 13:17 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldWidget/JavaScriptAssetUrlWidget.php
> +      '#default_value' => !$item->isEmpty() ? $item->environment : '',
It is a very minor comment and current how it is done shouldn't break anything.
But if we follow strictly to documentation: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21Select.php/class/Select/8.8.x
`#default_value: Must be NULL or not set in case there is no value for the element yet, in which case a first default option is inserted by default. Whether this first option is a valid option depends on whether the field is #required or not.`

2021-07-19 13:35 UTC, brummbar approved these changes

2021-07-19 14:20 UTC, merged