EWPP-846: Create formatter for JavaScript asset media.
openeuropa/oe_media pull request #168
Opened 2021-06-25 14:50 UTC by nagyad

2021-07-12 15:46 UTC, brummbar requested changes

2021-07-12 15:46 UTC, brummbar commented on modules/oe_media_js_asset/tests/src/Kernel/JavaScriptAssetUrlFormatterTest.php
> +    $this->mediaType = $media_type;
This is not needed, we are hardcoding the id in line 79.

2021-07-12 15:46 UTC, brummbar commented on modules/oe_media_js_asset/tests/src/Kernel/JavaScriptAssetUrlFormatterTest.php
> +    $this->display = $view_display;
Also this is not needed, as written below the media id is passed to the method so we can just load the display in the (only) test method below.

2021-07-12 15:46 UTC, brummbar commented on modules/oe_media_js_asset/tests/src/Kernel/JavaScriptAssetUrlFormatterTest.php
> +    $this->assertRaw('<script type="application/json" src="https://acceptance.europa.eu/webassets/somejavascript.js"></script>');
We need to add coverage for:

- rendering of multiple js assets;
- rendering a non-existing environment configured.

2021-07-15 22:32 UTC, brummbar approved these changes
I pushed some commits to fix the tests and minor code readability.

2021-07-19 14:48 UTC, brummbar approved these changes

2021-07-19 17:39 UTC, sergepavle requested changes
Few very minor comments.
Didn't find anything in scope of EPIC regarding browser caching. Drupal core originally adds query arguments for possibility control browser caching with using `$query_string = $this->state->get('system.css_js_query_string', '0');`
value.
Is it reasonable to add support of this capability? Is it should be separate ticket?

2021-07-19 17:39 UTC, sergepavle commented on modules/oe_media_js_asset/src/Plugin/Field/FieldFormatter/JavaScriptAssetUrlFormatter.php
> +            'type' => 'application/javascript',
Seems like according to this article https://developer.mozilla.org/ru/docs/Web/HTML/Element/script it is redundant in HTML5 use `type` attribute. Drupal core for instance doing exposing javascript files without type attribute as well.

2021-07-19 17:39 UTC, sergepavle commented on modules/oe_media_js_asset/tests/src/Kernel/JavaScriptAssetUrlFormatterTest.php
> + * Tests the field JS asset url formatter.
```suggestion
 * Tests the field JS asset URL formatter.
```

2021-07-22 15:52 UTC, sergepavle approved these changes

2021-07-23 07:34 UTC, merged