EWPP-1300: Using the OE OEmbed component.
openeuropa/oe_media pull request #170
Opened 2021-07-20 08:08 UTC by upchuk

2021-08-06 08:43 UTC, 22Alexandra approved these changes

2021-08-06 15:04 UTC, sergepavle requested changes

2021-08-09 10:23 UTC, upchuk commented on modules/oe_media_embed/oe_media_embed.post_update.php
> +    }
We keep the same icon.

2021-08-09 11:19 UTC, sergepavle approved these changes

2021-08-09 11:43 UTC, 22Alexandra submitted a review, later dismissed

2021-09-16 11:20 UTC, 22Alexandra approved these changes

2021-09-16 11:20 UTC, sergepavle approved these changes

2021-09-16 11:21 UTC, merged