EWPP-1355: Add createAccess check to media creation IEF.
openeuropa/oe_media pull request #175
Opened 2021-07-28 15:41 UTC by 22Alexandra

2021-08-02 08:30 UTC, brummbar requested changes

2021-08-02 08:30 UTC, brummbar commented on tests/src/FunctionalJavascript/MediaCreationFormWidgetTest.php
> +    // bundles can be created.
```suggestion
    // bundles can be created, as the iframe media cannot be referenced by the field.
```

2021-08-02 08:30 UTC, brummbar commented on tests/src/FunctionalJavascript/MediaCreationFormWidgetTest.php
> +    $permissions = [
Since the iframe media cannot be referenced, here we are not testing that bundles we don't have access to create are removed from the list. We should first skip one permission and see that the related entry is not available, and then add that too and check that all the allowed bundles are available. This way we cover all the scenarios.

2021-08-02 08:30 UTC, brummbar commented on tests/src/FunctionalJavascript/MediaCreationFormWidgetTest.php
> +    // target bundles (Note: Iframe should not be available).
The field doesn't allow to reference iframe in the first place.

2021-08-02 08:30 UTC, brummbar commented on tests/src/FunctionalJavascript/MediaCreationFormWidgetTest.php
> +    // target bundles (Note: Iframe should not be available).
Below there are some more cases where we can use assertSession(), let's take the chance to replace them.

2021-08-02 12:32 UTC, brummbar approved these changes

2021-08-03 09:06 UTC, imanoleguskiza approved these changes

2021-08-04 08:53 UTC, merged