EWPP-1911: Update to PHP7.4/8.0
openeuropa/oe_media pull request #185
Opened 2022-02-02 10:48 UTC by hernani

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-02-03 16:12 UTC, nagyad requested changes

2022-02-03 16:12 UTC, nagyad commented on composer.json
> +            "dealerdirect/phpcodesniffer-composer-installer": true
Should be in alphabetic order.

2022-02-03 16:12 UTC, nagyad commented on composer.json
> +        "Explicit requirement of behat module due to PHP8 compatibility.",
Explicit requirement of behat/behat module due to PHP8 compatibility.

2022-02-03 16:12 UTC, nagyad commented on composer.json
> +        "We use the drupaltest/behat-traits feature branch until it gets merged and the package is ready for Drupal 9.",
This can be removed.

2022-02-04 09:18 UTC, nagyad submitted a review, later dismissed

2022-02-04 10:43 UTC, 22Alexandra approved these changes

2022-02-04 10:43 UTC, 22Alexandra commented on composer.json
> +        "phpunit/phpunit": "^9.4",
We don't need this. Let's reorder alphabetically.

2022-02-07 11:09 UTC, nagyad submitted a review, later dismissed

2022-02-07 11:09 UTC, 22Alexandra approved these changes

2022-02-07 11:16 UTC, 22Alexandra approved these changes

2022-02-07 11:27 UTC, nagyad approved these changes

2022-02-07 11:30 UTC, merged