EWPP-1715: Create the Generic Webtools media type.
openeuropa/oe_media pull request #187
Opened 2022-02-12 09:26 UTC by yenyasinn

2022-02-25 12:26 UTC, 22Alexandra requested changes

2022-02-25 12:26 UTC, 22Alexandra commented on modules/oe_media_webtools/config/install/field.field.media.webtools_generic.oe_media_webtools.yml
> +description: 'Enter the snippet without the script tag. Snippets can be generated in <a href="https://europa.eu/webtools/mgmt/wizard/">Webtools wizard</a>.'
We need to open the wizard in a new tab (the same as for the other webtools media types).

2022-03-01 13:40 UTC, 22Alexandra approved these changes

2022-03-08 17:42 UTC, sergepavle submitted a review, later dismissed

2022-03-08 17:42 UTC, sergepavle commented on composer.json
> +        "Requiring composer/xdebug-handler until PHPMD 2.12 is released"
```suggestion
        "Requiring composer/xdebug-handler until PHPMD 2.12 is released."
```

2022-03-09 16:25 UTC, 22Alexandra requested changes

2022-03-09 16:25 UTC, 22Alexandra commented on composer.json
> +        "composer/xdebug-handler": "^2.0",
Please remove this as it has been fixed in code-review: https://github.com/openeuropa/code-review/blob/2.x/composer.json#L7

2022-03-10 07:55 UTC, 22Alexandra approved these changes

2022-04-05 08:30 UTC, merged