EWPP-2023: Add "Given the following AV Portal video" command.
openeuropa/oe_media pull request #188
Opened 2022-03-12 16:23 UTC by yenyasinn

2022-03-14 08:13 UTC, 22Alexandra approved these changes

2022-03-22 09:25 UTC, brummbar requested changes
This step is not even used in this repo, this shouldn't be merged.

2022-03-22 09:36 UTC, yenyasinn commented
> This step is not even used in this repo, this shouldn't be merged.

It is used in EWCMS.
What should we do - move this step there, or add some tests that use it?
It was added here since other media have such steps in oe_media

2022-03-22 09:43 UTC, brummbar commented
The code should be used in a test scenario, so we know that it works. Also split commited code in multiple commits based on the reason of the commit itself. The test fixes don't belong in the same commit as the behat step.

2022-03-25 16:47 UTC, nagyad submitted a review, later dismissed

2022-04-06 14:56 UTC, 22Alexandra approved these changes

2022-04-06 15:51 UTC, nagyad approved these changes

2022-04-06 15:53 UTC, merged