EWPP-1570: Add Webtools countdown media type.
openeuropa/oe_media pull request #192
Opened 2022-04-13 09:28 UTC by 22Alexandra

2022-04-13 18:56 UTC, sergepavle commented on modules/oe_media_webtools/config/install/field.field.media.webtools_countdown.oe_media_webtools.yml
> +translatable: true
```suggestion
translatable: false
```

2022-04-13 18:56 UTC, sergepavle commented on modules/oe_media_webtools/config/post_updates/00004_webtools_countdown/field.field.media.webtools_countdown.oe_media_webtools.yml
> +translatable: true
```suggestion
translatable: false
```

2022-04-19 10:48 UTC, sergepavle approved these changes

2022-04-19 12:33 UTC, nagyad requested changes

2022-04-19 12:46 UTC, nagyad approved these changes

2022-04-19 13:20 UTC, sergepavle approved these changes

2022-04-25 06:30 UTC, sergepavle approved these changes

2022-04-25 06:44 UTC, upchuk approved these changes
Blind

2022-04-25 06:44 UTC, merged