EWPP-2358: Drupal 9.4 support.
openeuropa/oe_media pull request #196
Opened 2022-06-20 17:44 UTC by yenyasinn

2022-06-23 16:54 UTC, 22Alexandra commented on composer.json
> +        "Explicit minimum version requirement for fabpot/goutte due to lower version doesn't work with Drupal 9.3."
```suggestion
        "Explicit minimum version requirement for fabpot/goutte due to Drupal 9.3 compatibility."
```

2022-06-23 16:55 UTC, 22Alexandra requested changes

2022-06-23 16:55 UTC, 22Alexandra commented on modules/oe_media_avportal/config/install/views.view.av_portal_entity_browsers.yml
> -core_version_requirement: ^9.2
Why removing it entirely?

2022-06-23 16:55 UTC, 22Alexandra commented on modules/oe_media_avportal/tests/modules/oe_media_avportal_test/config/install/views.view.av_portal_entity_browser_test.yml
> -core_version_requirement: ^9.2
Why removing it entirely?

2022-06-23 16:55 UTC, 22Alexandra commented on modules/oe_media_avportal/tests/modules/oe_media_avportal_test/config/install/views.view.av_portal_test.yml
> -core_version_requirement: ^9.2
Why removing it entirely?

2022-06-24 10:48 UTC, yenyasinn commented on modules/oe_media_avportal/config/install/views.view.av_portal_entity_browsers.yml
> -core_version_requirement: ^9.2
Do we use core_version_requirement in configuration files?

2022-06-24 10:49 UTC, yenyasinn commented on modules/oe_media_avportal/tests/modules/oe_media_avportal_test/config/install/views.view.av_portal_entity_browser_test.yml
> -core_version_requirement: ^9.2
Do we use core_version_requirement in configuration files?

2022-06-24 10:49 UTC, yenyasinn commented on modules/oe_media_avportal/tests/modules/oe_media_avportal_test/config/install/views.view.av_portal_test.yml
> -core_version_requirement: ^9.2
Do we use core_version_requirement in configuration files?

2022-06-24 14:05 UTC, 22Alexandra commented on modules/oe_media_avportal/config/install/views.view.av_portal_entity_browsers.yml
> -core_version_requirement: ^9.2
Right.

2022-06-24 14:05 UTC, 22Alexandra approved these changes

2022-06-27 15:16 UTC, nagyad approved these changes

2022-06-30 08:41 UTC, merged