EWPP-2832: Add Iframe title to media types using the Iframe source.
openeuropa/oe_media pull request #211
Opened 2022-11-28 13:39 UTC by 22Alexandra

2022-11-29 15:12 UTC, nagyad requested changes

2022-11-29 15:12 UTC, nagyad commented on modules/oe_media_iframe/config/install/field.field.media.iframe.oe_media_iframe_title.yml
> +required: false
Should be required.

2022-11-29 15:12 UTC, nagyad commented on modules/oe_media_iframe/config/install/field.field.media.video_iframe.oe_media_iframe_title.yml
> +required: false
Should be required.

2022-11-29 15:12 UTC, nagyad commented on modules/oe_media_iframe/oe_media_iframe.post_update.php
> +      ->getStorage('field_config')
Make a field config storage variable outside of the loop.

2022-11-29 15:12 UTC, nagyad commented on modules/oe_media_iframe/oe_media_iframe.post_update.php
> +        'description' => 'Providing an Iframe title value will replace the title value in the iframe html.',
Provides an Iframe title value which will replace the title value in the iframe html.

2022-11-29 15:12 UTC, nagyad commented on modules/oe_media_iframe/oe_media_iframe.post_update.php
> +        'required' => FALSE,
Should be required.

2022-11-29 15:12 UTC, nagyad commented on modules/oe_media_iframe/src/Plugin/media/Source/Iframe.php
> +        'description' => 'Providing an Iframe title value will replace the title value in the iframe html.',
Providing an Iframe title value will replace the title value in the iframe html.

2022-11-29 15:12 UTC, nagyad commented on modules/oe_media_iframe/src/Plugin/media/Source/Iframe.php
> +        'required' => FALSE,
Should be required.

2022-11-30 16:04 UTC, sergepavle commented on modules/oe_media_iframe/src/Plugin/Field/FieldFormatter/MediaIframeFormatter.php
> +      $media = $item->getEntity();
Is it intentional that it is done not within oe_theme or in some additional format filter?

2022-11-30 16:42 UTC, sergepavle approved these changes

2022-12-02 14:45 UTC, imanoleguskiza approved these changes

2022-12-05 08:42 UTC, merged